services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\OAuth2Server\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/DTO/*'
      - '../Classes/Domain/Repository/*'
      - '../Classes/OpenId/*'

  #Repositories
  FGTCLB\OAuth2Server\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'
    public: true

  # Services
  FGTCLB\OAuth2Server\Service\:
    resource: '../Classes/Service/*'
    public: true
