services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\OAuth2Server\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Repository/*'

  FGTCLB\OAuth2Server\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'
    public: true
